{
  "uid": "6e1ac15ab2aa6712",
  "name": "test_delcontact",
  "fullName": "test_contact.TestContact#test_delcontact",
  "historyId": "8e762da2be401352d7fdbd6f2e409651",
  "time": {
    "start": 1595992303484,
    "stop": 1595992326296,
    "duration": 22812
  },
  "status": "passed",
  "flaky": false,
  "newFailed": false,
  "beforeStages": [
    {
      "name": "_Class__pytest_setup_class",
      "time": {
        "start": 1595992295540,
        "stop": 1595992295540,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "attachmentsCount": 0,
      "shouldDisplayMessage": false,
      "stepsCount": 0,
      "hasContent": false
    }
  ],
  "testStage": {
    "status": "passed",
    "steps": [],
    "attachments": [
      {
        "uid": "5d4c6a05e1f08b83",
        "name": "log",
        "source": "5d4c6a05e1f08b83.txt",
        "type": "text/plain",
        "size": 984
      },
      {
        "uid": "6cb0641b030ca36d",
        "name": "stdout",
        "source": "6cb0641b030ca36d.txt",
        "type": "text/plain",
        "size": 299
      },
      {
        "uid": "93b6f0ee96bb7dad",
        "name": "stderr",
        "source": "93b6f0ee96bb7dad.txt",
        "type": "text/plain",
        "size": 662
      }
    ],
    "parameters": [],
    "attachmentsCount": 3,
    "shouldDisplayMessage": false,
    "stepsCount": 0,
    "hasContent": true
  },
  "afterStages": [
    {
      "name": "_Class__pytest_setup_class::0",
      "time": {
        "start": 1595992332042,
        "stop": 1595992332190,
        "duration": 148
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "attachmentsCount": 0,
      "shouldDisplayMessage": false,
      "stepsCount": 0,
      "hasContent": false
    }
  ],
  "labels": [
    {
      "name": "suite",
      "value": "test_contact"
    },
    {
      "name": "subSuite",
      "value": "TestContact"
    },
    {
      "name": "host",
      "value": "X8O0ILYDG7L3A0P"
    },
    {
      "name": "thread",
      "value": "61404-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "test_contact"
    },
    {
      "name": "resultFormat",
      "value": "allure2"
    }
  ],
  "parameters": [],
  "links": [],
  "hidden": false,
  "retry": false,
  "extra": {
    "severity": "normal",
    "retries": [
      {
        "uid": "c87560eb533a15c5",
        "status": "broken",
        "statusDetails": "UnboundLocalError: local variable 'result_before' referenced before assignment",
        "time": {
          "start": 1595992101305,
          "stop": 1595992120445,
          "duration": 19140
        }
      },
      {
        "uid": "44c5bc9a726791b",
        "status": "broken",
        "statusDetails": "NameError: name 'Context' is not defined",
        "time": {
          "start": 1595991861061,
          "stop": 1595991867385,
          "duration": 6324
        }
      },
      {
        "uid": "f56396d3d984e7b3",
        "status": "broken",
        "statusDetails": "TypeError: object of type 'NoneType' has no len()",
        "time": {
          "start": 1595991362383,
          "stop": 1595991380901,
          "duration": 18518
        }
      },
      {
        "uid": "3554d0f843ece3aa",
        "status": "broken",
        "statusDetails": "TypeError: object of type 'NoneType' has no len()",
        "time": {
          "start": 1595991181461,
          "stop": 1595991201308,
          "duration": 19847
        }
      },
      {
        "uid": "7ef3ed2b95b83947",
        "status": "broken",
        "statusDetails": "AttributeError: 'NoneType' object has no attribute 'person_setting'",
        "time": {
          "start": 1595991128967,
          "stop": 1595991135289,
          "duration": 6322
        }
      },
      {
        "uid": "2293365917c32db",
        "status": "broken",
        "statusDetails": "TypeError: get_contact() missing 1 required positional argument: 'name'",
        "time": {
          "start": 1595991039284,
          "stop": 1595991060566,
          "duration": 21282
        }
      },
      {
        "uid": "6b0a98f5364e9936",
        "status": "broken",
        "statusDetails": "AttributeError: 'NoneType' object has no attribute 'person_setting'",
        "time": {
          "start": 1595989518705,
          "stop": 1595989528433,
          "duration": 9728
        }
      },
      {
        "uid": "da43671073982341",
        "status": "broken",
        "statusDetails": "AttributeError: 'NoneType' object has no attribute 'person_setting'",
        "time": {
          "start": 1595989313804,
          "stop": 1595989323541,
          "duration": 9737
        }
      },
      {
        "uid": "8c0769ee70c489af",
        "status": "broken",
        "statusDetails": "AttributeError: 'NoneType' object has no attribute 'person_setting'",
        "time": {
          "start": 1595989124117,
          "stop": 1595989133969,
          "duration": 9852
        }
      },
      {
        "uid": "4510aabea0f318ce",
        "status": "broken",
        "statusDetails": "AttributeError: 'NoneType' object has no attribute 'person_setting'",
        "time": {
          "start": 1595989006480,
          "stop": 1595989013293,
          "duration": 6813
        }
      },
      {
        "uid": "5b5c26f40c86d443",
        "status": "broken",
        "statusDetails": "AttributeError: 'NoneType' object has no attribute 'person_setting'",
        "time": {
          "start": 1595988737276,
          "stop": 1595988744598,
          "duration": 7322
        }
      },
      {
        "uid": "efe66fae00c68c0d",
        "status": "broken",
        "statusDetails": "AttributeError: 'NoneType' object has no attribute 'person_setting'",
        "time": {
          "start": 1595988585666,
          "stop": 1595988592531,
          "duration": 6865
        }
      },
      {
        "uid": "de0d73ebbf6a3b84",
        "status": "broken",
        "statusDetails": "TypeError: get_contact() missing 1 required positional argument: 'name'",
        "time": {
          "start": 1595988284146,
          "stop": 1595988289219,
          "duration": 5073
        }
      },
      {
        "uid": "65ef0dad0eb8fe87",
        "status": "broken",
        "statusDetails": "TypeError: object of type 'NoneType' has no len()",
        "time": {
          "start": 1595945408529,
          "stop": 1595945433658,
          "duration": 25129
        }
      },
      {
        "uid": "476ff433d477c559",
        "status": "broken",
        "statusDetails": "TypeError: object of type 'NoneType' has no len()",
        "time": {
          "start": 1595945231454,
          "stop": 1595945261443,
          "duration": 29989
        }
      },
      {
        "uid": "7f0eab50ac4abbe",
        "status": "broken",
        "statusDetails": "AttributeError: 'NoneType' object has no attribute 'person_setting'",
        "time": {
          "start": 1595945168729,
          "stop": 1595945175985,
          "duration": 7256
        }
      },
      {
        "uid": "2f2486e06fc3eebe",
        "status": "broken",
        "statusDetails": "TypeError: object of type 'NoneType' has no len()",
        "time": {
          "start": 1595944871505,
          "stop": 1595944901898,
          "duration": 30393
        }
      },
      {
        "uid": "904c763bcf85cd1a",
        "status": "broken",
        "statusDetails": "NameError: name 'num' is not defined",
        "time": {
          "start": 1595944783581,
          "stop": 1595944789043,
          "duration": 5462
        }
      },
      {
        "uid": "46b1546ebaf5a1cf",
        "status": "broken",
        "statusDetails": "TypeError: object of type 'NoneType' has no len()",
        "time": {
          "start": 1595944616084,
          "stop": 1595944645788,
          "duration": 29704
        }
      },
      {
        "uid": "e9c36255902d596d",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.TimeoutException: Message:",
        "time": {
          "start": 1595944297531,
          "stop": 1595944326839,
          "duration": 29308
        }
      },
      {
        "uid": "952323ae2eafd74c",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.tencent.wework' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:7555 shell am start -W -n com.tencent.wework/.launch.WwMainActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability",
        "time": {
          "start": 1595944234144,
          "stop": 1595944234144,
          "duration": 0
        }
      },
      {
        "uid": "90e9535fe17c2e1e",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.TimeoutException: Message:",
        "time": {
          "start": 1595943997563,
          "stop": 1595944039579,
          "duration": 42016
        }
      },
      {
        "uid": "aa91b9ffacc26737",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.tencent.wework' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:7555 shell am start -W -n com.tencent.wework/.launch.WwMainActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability",
        "time": {
          "start": 1595943929345,
          "stop": 1595943929345,
          "duration": 0
        }
      },
      {
        "uid": "3ce57239c9566ae8",
        "status": "broken",
        "statusDetails": "AttributeError: 'list' object has no attribute 'click'",
        "time": {
          "start": 1595943892861,
          "stop": 1595943899663,
          "duration": 6802
        }
      },
      {
        "uid": "2b547a47c5cf4229",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.tencent.wework' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:7555 shell am start -W -n com.tencent.wework/.launch.WwMainActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability",
        "time": {
          "start": 1595943852157,
          "stop": 1595943852157,
          "duration": 0
        }
      },
      {
        "uid": "2d251c4b3c356dd4",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.TimeoutException: Message:",
        "time": {
          "start": 1595943714385,
          "stop": 1595943743300,
          "duration": 28915
        }
      },
      {
        "uid": "5dec12b2c2a96e75",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.tencent.wework' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:7555 shell am start -W -n com.tencent.wework/.launch.WwMainActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability",
        "time": {
          "start": 1595943653104,
          "stop": 1595943653104,
          "duration": 0
        }
      },
      {
        "uid": "1b0dba2b5b0492d3",
        "status": "failed",
        "statusDetails": "AssertionError: assert (1 - 1) == 2\n +  where 1 = len([<appium.webdriver.webelement.WebElement (session=\"5c4787a7-202b-40b0-8500-593bb4f0d626\", element=\"d9dd4341-a4a2-455a-911a-e459d1c0cd7a\")>])\n +  and   2 = len([<appium.webdriver.webelement.WebElement (session=\"5c4787a7-202b-40b0-8500-593bb4f0d626\", element=\"3df80373-eff8-4262-...ebelement.WebElement (session=\"5c4787a7-202b-40b0-8500-593bb4f0d626\", element=\"89e20879-75f2-464d-8890-b6bdc7357c9c\")>])",
        "time": {
          "start": 1595942444330,
          "stop": 1595942471999,
          "duration": 27669
        }
      },
      {
        "uid": "cf275112d11110",
        "status": "broken",
        "statusDetails": "AttributeError: 'NoneType' object has no attribute 'person_setting'",
        "time": {
          "start": 1595942311240,
          "stop": 1595942330459,
          "duration": 19219
        }
      },
      {
        "uid": "723e11e01fafd74b",
        "status": "broken",
        "statusDetails": "TypeError: 'NoneType' object is not subscriptable",
        "time": {
          "start": 1595942100734,
          "stop": 1595942134644,
          "duration": 33910
        }
      },
      {
        "uid": "b5398c99a02e12b5",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.tencent.wework' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:7555 shell am start -W -n com.tencent.wework/.launch.WwMainActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability",
        "time": {
          "start": 1595942047074,
          "stop": 1595942047074,
          "duration": 0
        }
      },
      {
        "uid": "49f2b1ee179bb8bb",
        "status": "broken",
        "statusDetails": "AttributeError: 'SearchPage' object has no attribute 'search_contact'",
        "time": {
          "start": 1595941853347,
          "stop": 1595941865840,
          "duration": 12493
        }
      },
      {
        "uid": "2a53d61d40f5f77b",
        "status": "broken",
        "statusDetails": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C6E9AF9DA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
        "time": {
          "start": 1595941786748,
          "stop": 1595941786748,
          "duration": 0
        }
      },
      {
        "uid": "9d2b1928f64f35db",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.tencent.wework' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:7555 shell am start -W -n com.tencent.wework/.launch.WwMainActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability",
        "time": {
          "start": 1595941719932,
          "stop": 1595941719932,
          "duration": 0
        }
      },
      {
        "uid": "73b439e2d84f1442",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.TimeoutException: Message:",
        "time": {
          "start": 1595941108092,
          "stop": 1595941135766,
          "duration": 27674
        }
      },
      {
        "uid": "a8ce63a9b5246bc2",
        "status": "passed",
        "time": {
          "start": 1595938352736,
          "stop": 1595938354005,
          "duration": 1269
        }
      },
      {
        "uid": "399ce5f88b31dc0a",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.tencent.wework' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:7555 shell am start -W -n com.tencent.wework/.launch.WwMainActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability",
        "time": {
          "start": 1595938271116,
          "stop": 1595938271116,
          "duration": 0
        }
      },
      {
        "uid": "20e4e948ac8f987e",
        "status": "passed",
        "time": {
          "start": 1595938249035,
          "stop": 1595938252840,
          "duration": 3805
        }
      },
      {
        "uid": "ddc5878e213d566e",
        "status": "broken",
        "statusDetails": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.tencent.wework' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:7555 shell am start -W -n com.tencent.wework/.launch.WwMainActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability",
        "time": {
          "start": 1595938154385,
          "stop": 1595938154385,
          "duration": 0
        }
      },
      {
        "uid": "e11eec01f526a82f",
        "status": "failed",
        "statusDetails": "AssertionError: assert '2' == 2",
        "time": {
          "start": 1595938098650,
          "stop": 1595938125383,
          "duration": 26733
        }
      },
      {
        "uid": "a19e513e93f56881",
        "status": "broken",
        "statusDetails": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017DF8733E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
        "time": {
          "start": 1595937988324,
          "stop": 1595937988324,
          "duration": 0
        }
      },
      {
        "uid": "8bb99af6bc39d4cb",
        "status": "broken",
        "statusDetails": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A02F362DA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
        "time": {
          "start": 1595937747756,
          "stop": 1595937747756,
          "duration": 0
        }
      }
    ],
    "categories": [],
    "tags": []
  },
  "source": "6e1ac15ab2aa6712.json",
  "parameterValues": []
}